@url = http://localhost:8080
@blogs = /api/blogs

GET {{url}}{{blogs}}

###
POST {{url}}{{blogs}}
Content-Type: application/json

{
  "author": "llfalcao",
  "likes": 15694,
  "title": "Backend Magic",
  "url": "backendmagic.com"
}