@url = http://localhost:8080
@notes = /api/notes

GET {{url}}{{notes}}

###
GET {{url}}{{notes}}/62269ae776308884ecd0a1c

###
POST {{url}}{{notes}}
Content-Type: application/json

{
  "content": "Keep coding",
  "important": true
}

###
DELETE {{url}}{{notes}}/62269afda63211036460b49