@url = http://localhost:8080
@notes = /api/notes

GET {{url}}{{notes}}

###
GET {{url}}{{notes}}/2

###
POST {{url}}{{notes}}
Content-Type: application/json

{
  "content": "Keep coding",
  "important": true
}

###
DELETE {{url}}{{notes}}/4