@url = http://localhost:8080
@notes = /api/notes

GET {{url}}{{notes}}

###
GET {{url}}{{notes}}/6227e4333907e8303c643

###
POST {{url}}{{notes}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZheWUiLCJpZCI6IjYyNTVmNzkwYmZiNTlmYjU3ZDIxMzZmMyIsImlhdCI6MTY1MjAzMjUyMn0.yprQyXzmanWDlYWt2_QFeOzuL0XA6mTi30cJI1Hk45s

{
  "content": "Keep coding",
  "important": true
}

###
PUT {{url}}{{notes}}/6227e4f23d33907e8303c642
Content-Type: application/json

{
  "content": "Keep coding",
  "important": false
}

###
DELETE {{url}}{{notes}}/6227e54d4c7a59970f5ca69d