@url = http://localhost:8080
@persons = /api/persons

GET {{url}}{{persons}}

###
GET {{url}}{{persons}}/6227f2a784c6519eea1c0575


###
POST {{url}}{{persons}}
Content-Type: application/json

{
  "name": "Somebody",
  "number": "555-123-4567"
}

###
PUT {{url}}{{persons}}/6227f2a784c6519eea1c0575
Content-Type: application/json

{
  "name": "Somebody",
  "number": "555-987-6543"
}

###
DELETE {{url}}{{persons}}/6227f2a784c6519eea1c0575