@url = http://localhost:8080
@persons = /api/persons

GET {{url}}{{persons}}

###
GET {{url}}{{persons}}/6226bd9725c6e25505cbdd63


###
POST {{url}}{{persons}}
Content-Type: application/json

{
  "name": "Somebody",
  "number": "555-123-4567"
}

###
PUT {{url}}{{persons}}/6226bf67fe8cedac1c6238c9
Content-Type: application/json

{
  "name": "Somebody",
  "number": "555-987-6543"
}

###
DELETE {{url}}{{persons}}/6226bd9c25c6e25505cbdd66