@url = http://localhost:8080
@users = /api/users

GET {{url}}{{users}}

###
GET {{url}}{{users}}/faye

###
POST {{url}}{{users}}
Content-Type: application/json

{
  "username": "faye",
  "name": "Faye",
  "password": "beyondTheWalls"
}

###
POST {{url}}{{users}}
Content-Type: application/json

{
  "username": "whatisapassword",
  "name": "HTTP Four Hundred"
}